config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  namespace :admin do
    resources :users
    resources :groceries
    resources :products
  end

  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :groceries do
    resources :products, controller: 'grocery_products'    
    resources :purchase_orders
    resources :reports
  end

  resources :reports, only:[] do
    resources :comments, only:[:index,:create], controller: 'report_comments'
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :products, only: [:index] do
    resources :reviews, only: [:show, :new, :create, :index, :edit, :update, :destroy]
  end


  match '/signup',    to: 'users#new',            via: 'get'
  match '/signin',    to: 'sessions#new',         via: 'get'
  match '/signout',   to: 'sessions#destroy',     via: 'delete'

  match '/groceries/:grocery_id/rate_product/:id', to: 'grocery_products#rate_product', via: 'post', as: 'rate_product'

  match '/groceries/:grocery_id/follow', to: 'groceries#follow', via: 'post', as: 'grocery_follow'
  match '/groceries/:grocery_id/unfollow', to: 'groceries#unfollow', via: 'post', as: 'grocery_unfollow'

  match '/reviews/:review_id/comments/new', to: 'review_comments#create', via: 'post', as: 'post_new_comment'
  match '/reviews/:review_id/comments', to: 'review_comments#index', via: 'get', as: 'review_comments'

  match '/groceries/:id/search_products', to: 'groceries#search_products', via: 'get', as: 'search_products'

  match '/search_groceries', to: 'search#groceries', via: 'get'
  match '/search_products',  to: 'search#products',  via: 'get'

  match '/users/:id/feed', to: 'users#news_feed', via: 'get', as:'user_news_feed'
  match '/users/:id/posted_news', to: 'users#posted_news', via: 'get', as: 'user_posted_news'
  match '/users/:id/following_groceries', to: 'users#following_groceries', via: 'get', as: 'user_following_groceries'
  match '/users/:id/associated_groceries', to: 'users#associated_groceries', via: 'get', as: 'user_associated_groceries'










end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div>
    <div>
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_grocery_form.html.erb
<%= form_for(grocery, url: namespace) do |f| %>

 	<%= render 'shared/error_messages', object: grocery %>

 	<div class = "field">
    <% if grocery.has_image? %>
      <%= image_tag grocery.grocery_image.grocery_image_url, :style => "width: 250px; height: 120px;"  %>
    <% else %>
      <%= image_tag "Springfield_grocery_store.png", :style => "width: 250px; height: 120px;"  %>
    <% end %>
    <br>
    <%= f.label :image, "Change Image" %>
    <%= f.file_field :image %>
  </div>

	<div class = "field">
		<%= f.label :name, "Name" %>
		<%= f.text_field :name %>
	</div>

	<div class = "field">
		<%= f.label :address, "Address" %>
		<%= f.text_field :address %>
	</div>

	<%= f.submit submit_message%>
<% end %>

app/views/shared/_grocery_products_pagination.html.erb
<% if @products.any? %>
	<strong>Products</strong>
	<%= will_paginate @products, params: {controller: 'groceries', action: 'search_products', grocery_id: @grocery.id} %>  

  <table border>
    <tr>
      <th>Name</th>
      <th>Image</th>
    	<th>Actions</th>
    </tr>   	
	<% @products.each do |product| %>  
		<tr>
			<td>
	      <%= link_to product.name, grocery_product_path(@grocery,product) %>  
	    </td>
	    <td>
		    <% if product.has_image? %>
				  <%= image_tag product.product_image.product_image_url, :style => "width: 50; height: 50px;"  %>
				<% else %>
				  <%= image_tag "products-icon-basket.gif", :style => "width: 50px; height: 50px;"  %>
				<% end %>
			</td>
			<td>
				<%= link_to "Show", grocery_product_path(@grocery,product) %>
		    <% if @privilege == :administrator %>
		      | <%= link_to "Edit", edit_grocery_product_path(@grocery,product) %>
		      | <%= link_to 'Destroy', grocery_product_path(@grocery,product), method: :delete, data: { confirm: 'Are you sure?' } %>
		    <% end %>
	    </td>
    </tr>
	<% end %>  	
  </table>

	<%= will_paginate @products, params: {controller: 'groceries', action: 'search_products', grocery_id: @grocery.id} %>  
<% else %>
	<span>No products found</span>
<% end %>

app/views/shared/_grocery_reports_pagination.html.erb
<% if @reports.any? %>
	<br>
	<h2>News</h2>
	<%= will_paginate @reports, params: {controller: 'grocery_reports', action: 'index', grocery_id: @grocery.id} %>
	<% @reports.each do |report| %>

		<div class="report-container">
			<h4><%= report.title %></h4>

			<% if report.product %>
				<% if report.product.has_image? %>
					<%= image_tag report.product.product_image.product_image_url, :style => "width: 50; height: 50px;"  %>
				<% else %>
					<%= image_tag "products-icon-basket.gif", :style => "width: 50px; height: 50px;"  %>
				<% end %>
			<% end %>

			<%= simple_format(report.text) %>

			<% if report.product %>
				<a href="<%= grocery_product_path(@grocery, report.product) %>">
					<span class="link-spanner"></span>
				</a>
			<% end %>

			<% if @privilege == :administrator %>
				<table class="report-admin">
					<tr>
						<td><%= link_to "Edit", edit_grocery_report_path(@grocery, report) %></td>
						<td><%= link_to "Destroy", grocery_report_path(@grocery, report), data: { confirm: "Are you sure?" , method: :delete } %></td>
					</tr>
				</table>
				<clear-fix></clear-fix>
			<% end %>

		</div>
		<br>

	<% end %>
	<%= will_paginate @reports, params: {controller: 'grocery_reports', action: 'index', grocery_id: @grocery.id} %>
<% end %>

app/views/shared/_product_form.html.erb
<!-- remember to provide local variables product, namespace and submit_message -->

<%= form_for(product, url: namespace) do |f| %>

  <%= render 'shared/error_messages', object: product %>

  <div class = "field">
    <% if product.has_image? %>
      <%= image_tag product.product_image.product_image_url, :style => "width: 250px; height: 120px;"  %>
    <% else %>
      <%= image_tag "products-icon-basket.gif", :style => "width: 250px; height: 120px;"  %>
    <% end %>
    <br>
    <%= f.fields_for :product_image do |ff| %>
      <%= ff.label :product_image, "Change Image" %>
      <%= ff.file_field :product_image %>
    <% end %>
  </div>

  <div class = "field">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
  </div>

  <%= f.fields_for :inventory do |ff| %>
    <div class="field">
      <%= ff.label :stock, "Stock" %>
      <%= ff.number_field :stock, step: 0.01 %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price, "Price" %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :description, "Description" %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :visible, "Visible" %>
    <%= f.check_box :visible %>
  </div>


  <% @show_existing = (product.category_mode == :existing_category) %>

  <div class = "field">
    <%= f.radio_button :category_mode, "existing_category", checked: @show_existing, onclick: "switchCategoryMode(this)" %>
    <%= f.label :category_mode, 'Choose an existing category', value: "existing_category" %>
    <br>
    <%= f.radio_button :category_mode, "new_category", checked: !@show_existing, onclick: "switchCategoryMode(this)" %>
    <%= f.label :category_mode, 'Create and assign a new category', value: "new_category" %>
    <br>
    <div id = "existing_category_div" <%= @show_existing ? '' : 'class=hide-element'%>>
      <%= f.label :existing_category, "Existing Category: " %>
      <br>
      <%= f.select :existing_category, options_for_select(Category.all.collect {|c| [c.name,c.id]}, product.existing_category ) , {include_blank: true}, {class: 'awesome-select'} %>
    </div>
    <div id = "new_category_div" <%= !@show_existing ? '' : 'class=hide-element'%>>
      <%= f.label :new_category, "New Category: " %>
      <br>
      <%= f.text_field :new_category %>
    </div>
  </div>

  <div class = "field">
    <div>
      <%= f.label :existing_tags, "Existing Tags" %>
      <br>
      <%= f.select :existing_tags, options_for_select(Tag.all.collect {|tag| [tag.name,tag.id]}, product.existing_tags ), {}, {multiple: true, class: 'awesome-select'} %>
    </div>
    <div>
      <%= f.label :new_tags, "New Tags: " %>
      <%= f.text_field :new_tags, id: 'new_tags', value: product.new_tags %>
    </div>
  </div>

  <%= f.submit submit_message %>

<% end %>

<script type="text/javascript">
  $(document).ready(function() {
    $(".awesome-select").select2({
      width: "230px"
    });
    $("#new_tags").tagsInput();
  });

  function switchCategoryMode(radio) {
    if(radio.value == "new_category") {
      $("#existing_category_div").addClass("hide-element");
      $("#new_category_div").removeClass("hide-element");

    } else {
      $("#existing_category_div").removeClass("hide-element");
      $("#new_category_div").addClass("hide-element");
    }
  }
</script>

app/views/shared/_product_view.html.erb
<!--
  parameters: product, grocery
 -->

<div class="product-container clearfix">

  <h1 style='display: inline-block;'><%= product.name %></h1>
  <% if is_administrator? %>
    <%= link_to 'edit', edit_grocery_product_path(grocery,product) %> |
    <%= link_to 'delete', grocery_product_path(grocery,product), method: :delete, data: { confirm: 'Do you really want to delete this product?' } %>
  <% end %>
  <br>
  by <%= link_to grocery.name, grocery_path(grocery) %>
  <br/>
  <br/>

  <div class="image-and-rating">

    <% if product.has_image? %>
      <%= image_tag product.product_image.product_image_url %>
    <% else %>
      <%= image_tag "products-icon-basket.gif" %>
    <% end %>
    <br/>

    <span class="stars-container">
      <span class="stars-row back">
         <label>★</label><label>★</label><label>★</label><label>★</label><label>★</label>
      </span>
      <span class="stars-row front" style="width: <%= product.star_count.get_rating_percentage_average %>%">
         <label>★</label><label>★</label><label>★</label><label>★</label><label>★</label>
      </span>
    </span>
    (<%= product.stars.count %>)
    <br/>

    <%= product.star_count.get_rating_average.round(1) %> out of  5 stars
    <br/>

    <%= link_to "see all reviews (#{product.reviews.count})", product_reviews_path(product) %>

  </div>


  <div class="extra-info">
    Price: $ <%= product.price %> <br/>
    IN STOCK: <%= product.inventory.stock %> <br/>
    <p>
      <strong>Category:</strong>
      <%= @product.category ? @product.category.name : "none" %>
    </p>
    <p>
      <strong>Tags:</strong>
      <%= @product.tags.any? ? @product.tags.map{|x| x.name}.join(', ') : 'none'%>
    </p>
  </div>

</div>

<% if @recipe_title %>
    <div>
        <div>Recipe: <%= link_to @recipe_title, @recipe_url %></div>
        <%= image_tag(@recipe_image, alt: '[Recipe picture]') %>
    </div>
<% end %>

app/views/shared/_product_with_rating_bars.html.erb
<%#=
  parameters: product, grocery
%> 

<div class="product-container clearfix">

  <% percentages = product.star_count.get_percentages %>

  <div class="rating-container">
    Customer Reviews <br/>

    <span class="stars-container">
      <span class="stars-row back">
         <label>★</label><label>★</label><label>★</label><label>★</label><label>★</label>
      </span>
      <span class="stars-row front" style="width: <%= product.star_count.get_rating_percentage_average %>%">
         <label>★</label><label>★</label><label>★</label><label>★</label><label>★</label>
      </span>
    </span>
    <br/>

    <%= product.star_count.get_rating_average.round(1) %> out of  5 stars
    <br/>
    <div class="rating-bars-container">
      5 star <div class="rating-bar"><span style="width: <%= percentages[4] %>%"></span></div> <%= percentages[4].round %>% <br/>
      4 star <div class="rating-bar"><span style="width: <%= percentages[3] %>%"></span> </div> <%= percentages[3].round %>% <br/>
      3 star <div class="rating-bar"> <span style="width: <%= percentages[2] %>%"></span> </div> <%= percentages[2].round %>% <br/>
      2 star <div class="rating-bar"> <span style="width: <%= percentages[1] %>%"></span></div> <%= percentages[1].round %>% <br/>
      1 star  <div class="rating-bar"><span style="width: <%= percentages[0] %>%"></span></div> <%= percentages[0].round %>% <br/>
    </div>
  </div>

  <div class = "left-floatme middle">
    <%= link_to grocery_product_path(grocery,product) do %>
      <strong><%= product.name %></strong>
    <% end %> <br/>
    by <%= link_to grocery.name, grocery_path(grocery) %> <br/>
    <% if product.has_image? %>
      <%= image_tag product.product_image.product_image_url %>
    <% else %>
      <%= image_tag "products-icon-basket.gif" %>
    <% end %>
  </div>

  <div class="left-floatme right">    
    Price: $ <%= product.price %> <br/>
    IN STOCK: <%= product.inventory.stock %> <br/>
    <strong>Category:</strong>
    <%= @product.category ? @product.category.name : "none" %> <br/>
    <strong>Tags:</strong>
    <%= @product.tags.any? ? @product.tags.map{|x| x.name}.join(', ') : 'none'%> <br/>
  </div>

</div>

app/views/shared/_purchase_orders_pagination.html.erb
<%= will_paginate @pagination_data %>  

<label>Showing <%= @purchases_data.count %> results: </label>
<table border>
  <tr>
    <th>Date</th>
    <th>Products Count</th>
  	<th>Total Price</th>
  	<th>Details</th>
  </tr>   	

<% @purchases_data.each do |row| %>  
	<tr>
		<td>
   		<%= row.purchase_date %>
    </td>
    <td>
    	<%= row.products_count %>
    </td>
    <td>
    	$ <%= row.total_price %>
    </td>
    <td>
    	<%= link_to 'see details', grocery_purchase_order_path(@grocery,row.order_id) %>
    </td>
  </tr>
<% end %>  	
</table>

<%= will_paginate @pagination_data %>

app/views/shared/_user_form.html.erb
<%= form_for(@user, url: @namespace) do |f| %>

  <h1>Create a new account</h1>

 	<%= render 'shared/error_messages', object: @user %>

  <div class = "field">
  	<%= f.label :first_name, "First Name" %>
  	<%= f.text_field :first_name %>
  </div>

  <div class = "field">
  	<%= f.label :last_name, "Last Name" %>
  	<%= f.text_field :last_name %>
  </div>

  <div class = "field">
  	<%= f.label :username, "Username" %>
  	<%= f.text_field :username %>
  </div>

  <div class = "field">
  	<%= f.label :password, "Password" %>
  	<%= f.password_field :password %>
  </div>

  <div class = "field">
  	<%= f.label :password_confirmation, "Confirm password" %>
  	<%= f.password_field :password_confirmation %>
  </div>

  <div class = "field">
  	<%= f.label :email, "Email" %>
  	<%= f.text_field :email %>
  </div>

  <div class = "field">
  	<%= f.label :address, "Address" %>
  	<%= f.text_field :address %>
  </div>

	<%= f.submit @submit_message %>
<% end %>