config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  namespace :admin do
    resources :users
    resources :groceries
    resources :products
  end

  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :groceries do
    resources :products, controller: 'grocery_products'    
    resources :purchase_orders
    resources :reports
  end

  resources :reports, only:[] do
    resources :comments, only:[:index,:create], controller: 'report_comments'
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :products, only: [:index] do
    resources :reviews, only: [:show, :new, :create, :index, :edit, :update, :destroy]
  end


  match '/signup',    to: 'users#new',            via: 'get'
  match '/signin',    to: 'sessions#new',         via: 'get'
  match '/signout',   to: 'sessions#destroy',     via: 'delete'

  match '/groceries/:grocery_id/rate_product/:id', to: 'grocery_products#rate_product', via: 'post', as: 'rate_product'

  match '/groceries/:grocery_id/follow', to: 'groceries#follow', via: 'post', as: 'grocery_follow'
  match '/groceries/:grocery_id/unfollow', to: 'groceries#unfollow', via: 'post', as: 'grocery_unfollow'

  match '/reviews/:review_id/comments/new', to: 'review_comments#create', via: 'post', as: 'post_new_comment'
  match '/reviews/:review_id/comments', to: 'review_comments#index', via: 'get', as: 'review_comments'

  match '/groceries/:id/search_products', to: 'groceries#search_products', via: 'get', as: 'search_products'

  match '/search_groceries', to: 'search#groceries', via: 'get'
  match '/search_products',  to: 'search#products',  via: 'get'

  match '/users/:id/feed', to: 'users#news_feed', via: 'get', as:'user_news_feed'
  match '/users/:id/posted_news', to: 'users#posted_news', via: 'get', as: 'user_posted_news'
  match '/users/:id/following_groceries', to: 'users#following_groceries', via: 'get', as: 'user_following_groceries'
  match '/users/:id/associated_groceries', to: 'users#associated_groceries', via: 'get', as: 'user_associated_groceries'










end

app/models/grocery.rb
class Grocery < ActiveRecord::Base
	attr_accessor :image

	has_many :privileges 	
	has_many :privileged_users, through: :privileges, source: :user

	has_many :followers
	has_many :follower_users, through: :followers, source: :user

	has_many :products, :dependent => :delete_all
	has_many :reports

	has_many :purchase_orders

	has_one :grocery_image, :dependent => :destroy

	validates :name, presence: true, length: { minimum: 1, maximum: 40 }, uniqueness: true
	validates :address, presence: true

	def has_image?
		return self.grocery_image && !self.grocery_image.grocery_image.blank?
	end

	def image_url_or_default
		return self.has_image? ? self.grocery_image.grocery_image_url : "Springfield_grocery_store.png"
	end

	def purchases_data (from_date, to_date)
		query = self.purchase_orders.joins(:order_lines).select('purchase_orders.id, purchase_orders.created_at as date, count(order_lines.*) as order_lines_count, sum(order_lines.amount * order_lines.product_price) as total_price').group('purchase_orders.id').order('purchase_orders.id desc')

		unless from_date.nil?
			query = query.where('purchase_orders.created_at >= ?',from_date)
		end

		unless to_date.nil?
			to_date = (Date.parse(to_date) + 1).to_s
			query = query.where('purchase_orders.created_at < ?',to_date)
		end

		return query
	end

	def get_categories
		Category.find_by_sql("select distinct c.id,c.name from categories
     as c, products as p where p.grocery_id = #{self.id} and c.id = p.category_id");
	end

	def  get_tags
		Tag.find_by_sql("select distinct t.id, t.name from tags as t, products_tags as pt, products as p
      where t.id = pt.tag_id and pt.product_id = p.id and p.grocery_id = #{self.id}")
	end

	def products_purchase_data_to_JSON
		json_str = "{"
		first = true
		self.products.each  do |p|
			if first
				first = false
			else
				json_str << ","
			end
			json_str << %Q["#{p.id}" : {"name": "#{p.name}", "stock": #{p.inventory.stock} }]
		end
		json_str << "}"
		return json_str.html_safe
	end

	def get_users_per_privilege
		users = User.joins(:privileges).where('privileges.grocery_id = ?',self.id).select('privilege, users.*')
		inv_privileges = Privilege.privileges.invert
		priv_users = {}
		users.each do |user|
			priv = inv_privileges[user.privilege]
			next if priv.nil?			
			priv_users[priv] ||= []
			priv_users[priv] << user
		end
		return priv_users
	end

end

app/controllers/admin/groceries_controller.rb
class Admin::GroceriesController < ApplicationController
  before_action :set_grocery, only: [:show, :edit, :update, :destroy]
  before_action :set_namespace


  def index
    @groceries = Grocery.all
  end

  def new
    @grocery = Grocery.new
    @submit_message = "Create grocery";
  end

  def edit
    @submit_message = "Edit grocery";
  end

  def show
    if(@grocery.nil?)
      flash[:error] = "ERROR: grocery with id #{params[:id]} could not be found"
      redirect_to admin_groceries_path
    end   
  end

  def create
    @grocery = Grocery.new(grocery_params)
    if @grocery.save
        flash[:success] = "SUCCESS: Grocery successfully created!"
        redirect_to admin_groceries_path
    else
      flash[:error] = "ERROR: grocery could not be created!"
      render 'new'
    end
  end

  def update
    if @grocery.update(grocery_params)
      flash[:success] = "Grocery successfully updated!"
      redirect_to admin_groceries_path
    else
      render 'edit'
    end
  end

  def destroy
    if(!@grocery.nil?)
      @grocery.destroy
      flash[:success] = "Grocery destroyed successfully!"
    else
      flash[:error] = "User was nil"
    end
    redirect_to admin_groceries_path
  end

  private

    def set_grocery
      begin
        @grocery = Grocery.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        @grocery = nil
      end
    end

    def grocery_params
      params.require(:grocery).permit(:name, :address);
    end

    def set_namespace
      grocery_exists = @grocery && !@grocery.new_record?
      @namespace = grocery_exists ? admin_grocery_path(@grocery) : admin_groceries_path
    end

end

app/controllers/groceries_controller.rb
class GroceriesController < ApplicationController
  include GroceryHelper

  before_action :set_logged_user_by_cookie
  before_action only: [:show, :edit, :update, :destroy, :search_products] do set_grocery_by_id(:id) end
  before_action :set_privilege_on_grocery, only: [:show, :edit, :update, :destroy]

  before_action :check_user_logged_in, only: [:new, :create, :edit, :update, :destroy]
  before_action only: [:search_products, :edit, :update, :destroy] do check_grocery_exists(:id) end
  before_action only: [:edit, :update, :destroy] do check_privilege_on_grocery(:administrator, :id) end

  before_action :set_grocery_categories, except:[:follow, :unfollow]
  before_action :set_grocery_tags, except:[:follow, :unfollow]

  def index

    filtered_params = global_search_params
    categories = filtered_params[:categories]
    tags = filtered_params[:tags]
    search_string = filtered_params[:search]

    page = 1
    per_page = 3
    @page_count = nil

    if filtered_params.has_key?(:page)
      page = filtered_params[:page].to_i if filtered_params[:page].is_i?
      page = 1 if page < 1
    end

    if filtered_params.has_key?(:page_count)
      @page_count = filtered_params[:page_count].to_i if filtered_params[:page_count].is_i?
      @page_count = nil unless @page_count >= 0
    end

    @has_search_string = !search_string.blank?
    @has_categories = categories && categories.count > 0
    @has_tags = tags && tags.count > 0

    cond_count = 0
    cond_count+=1 if @has_search_string
    cond_count+=1 if @has_categories
    cond_count+=1 if @has_tags

    if cond_count > 0

      query = "WITH "
      first = true
      i = 1

      if @has_search_string
        query << "gids#{i} as (SELECT g.id
          FROM groceries as g
          WHERE g.name ILIKE '%#{search_string}%')"
        first = false
        i+=1
      end

      if @has_tags
        query << "," unless first
        query <<
        "gids#{i} as (
          SELECT p.grocery_id as id
          FROM products as p, products_tags as pt #{first ? "" : ", gids#{i-1}"}
          WHERE #{first ? "" : "gids#{i-1}.id = p.grocery_id AND "} p.id = pt.product_id and pt.tag_id IN (
            #{tags.join(',')})
          GROUP BY p.grocery_id
          HAVING COUNT(DISTINCT pt.tag_id) = #{tags.count})"
        first = false
        i+=1
      end

      if @has_categories
        query << "," unless first
        query <<
        "gids#{i} as (SELECT p.grocery_id as id
          FROM products as p #{first ? "" : ", gids#{i-1}"}
          WHERE #{first ? "" : "gids#{i-1}.id = p.grocery_id AND "} p.category_id IN (#{categories.join(',')})
          GROUP BY p.grocery_id
          HAVING COUNT(DISTINCT p.category_id) = #{categories.count})"
        first = false
        i+=1
      end

      with_tab = "gids#{i-1}";

      if @page_count.nil?
        query << "SELECT g.*, count(*) over() as total_count
        FROM groceries as g, #{with_tab}
        WHERE #{with_tab}.id = g.id
        LIMIT #{per_page}
        OFFSET #{(page-1) * per_page}"
        @groceries = Grocery.find_by_sql(query)
        if(@groceries.count > 0)
          total_entries = @groceries[0][:total_count]
          @page_count = (total_entries / per_page.to_f).ceil
        else
          @page_count = 1
        end
      else
        query << "SELECT g.*
        FROM groceries as g, #{with_tab}
        WHERE #{with_tab}.id = g.id
        LIMIT #{per_page}
        OFFSET #{(page-1) * per_page}"
        @groceries = Grocery.find_by_sql(query)
      end

    else
      @groceries = Grocery.all.paginate(page: page, per_page: per_page)
      @page_count = @groceries.total_pages
    end

    @pagination_data = PaginationData.new(@page_count, page)

  end

  def new
    @grocery = Grocery.new
    @submit_message = "Create grocery";
  end

  def create

    filtered_params = grocery_params
    @grocery = Grocery.new(filtered_params.except(:image))

    if @grocery.save
      flash[:success] = "Grocery created successfully!"
      if(filtered_params[:image])

        @grocery.grocery_image = GroceryImage.create(
            grocery_image: filtered_params[:image],
            grocery_id: @grocery.id)
      end

      Privilege.create(
        user_id: @logged_user.id,
        grocery_id: @grocery.id,
        privilege: :administrator)

      redirect_to grocery_path(@grocery)
    else
      render 'new'
    end
  end

  def show
    @products = @grocery.products.paginate(page: 1, per_page: 10)
    @users_per_privilege = @grocery.get_users_per_privilege
  end

  def edit
  end

  def update

    filtered_params = grocery_params

    if @grocery.update(filtered_params.except(:image))
      flash[:success] = "Grocery updated successfully!"

      if(filtered_params[:image])
        if(@grocery.grocery_image)
          @grocery.grocery_image.update(grocery_image: filtered_params[:image])
        else
          @grocery.grocery_image = GroceryImage.create(
            grocery_image: filtered_params[:image],
            grocery_id: @grocery.id)
        end
      end

      redirect_to grocery_path(@grocery)
    else
      render 'edit'
    end
  end

  def follow
    head :ok

    begin
      if params[:to] == 'true'
        Follower.create(
          user_id: @logged_user.id,
          grocery_id: params[:grocery_id])
      else
        # ??? Follower.destroy_all({ user_id: @logged_user.id, grocery_id: params[:grocery_id] })
        @logged_user.following_groceries.destroy(params[:grocery_id])
      end
    rescue ActiveRecord::RecordNotFound
    end
  end

  def unfollow
    begin
      @logged_user.following_groceries.delete(params[:grocery_id])
      respond_to do |format|
        format.json { render json: nil, status: :ok }
      end
    rescue ActiveRecord::RecordNotFound
      respond_to do |format|
        format.json { render json: nil, status: :unprocessable_entity }
      end
    end
  end

  helper_method :current_user_following_grocery
  def current_user_following_grocery
    @logged_user.following_groceries.exists?(@grocery.id)
  end

  def search_products

    filtered_params = grocery_search_params
    categories = filtered_params[:categories]
    tags = filtered_params[:tags]
    search_string = filtered_params[:search]

    @products = @grocery.products.where("products.visible = true")

    if search_string && !search_string.blank?
      @products = @products.where("products.name ILIKE ?","%#{search_string}%")
    end
    if categories && categories.count > 0
      @products = @products.where('products.category_id IN (?)',categories.map{|x|x.to_i} )
    end
    if tags && tags.count > 0
      @products = @products.where("(SELECT COUNT(*) FROM products_tags as pt WHERE
       pt.product_id = products.id AND pt.tag_id in (?)) = ?",tags.map{|x|x.to_i},tags.count)
    end
    if params[:page]
      @products = @products.paginate(page: params[:page], per_page: 10)
    else
      @products = @products.paginate(page: 1, per_page: 10)
    end

  end

  private

    def grocery_params
      params.require(:grocery).permit(:name, :address,:image)
    end

    def grocery_search_params
      params.permit(:search, {categories: []}, {tags: []}, :page, :page_count)
    end

    def global_search_params
      params.permit(:search, {categories: []}, {tags: []}, :page)
    end

end

app/helpers/grocery_helper.rb
module GroceryHelper

  def set_grocery_by_id(grocery_key)
    @grocery = Grocery.find_by_id(params[grocery_key])
  end

  def set_privilege_on_grocery
    @privilege = nil
    return if(@grocery.nil?)

    if(@logged_user)
      @privilege = @logged_user.privileges.where('privileges.grocery_id = ?',@grocery.id).first
      if(@privilege)
        @privilege = @privilege.privilege.to_sym
      end
    end
  end

  def set_grocery_categories
    @grocery_categories = @grocery.get_categories if @grocery_categories
  end

  def set_grocery_tags
    @grocery_tags = @grocery.get_tags if @grocery_tags
  end

  def check_grocery_exists(grocery_key)
    unless @grocery
      raise ActionController::RoutingError.new("Grocery with id #{params[grocery_key]} not found")
    end
  end

  def check_privilege_on_grocery(privilege, grocery_key)
    unless @privilege == privilege
      raise ActionController::RoutingError.new("You (user_id = #{@logged_user.id}) need a privilege of #{privilege} on this grocery (id = #{params[grocery_key]}) to perform this action")
    end
  end

  def current_user_following_grocery
    @logged_user.following_groceries.exists?(@grocery.id)
  end

end

app/views/groceries/_associated_grocery.html.erb
<div class="associated-grocery-container" id="<%= grocery.id %>">
	<%= link_to grocery_path(grocery) do %>
	  <%= image_tag grocery.image_url_or_default, class: 'grocery-image' %>
	  <br>
		<strong><%= grocery.name %></strong>
	<% end %>
</div>

app/views/groceries/_following_grocery.html.erb
<div class="following-grocery-container" id="<%= grocery.id %>">
	<%= link_to grocery_path(grocery) do %>
	  <%= image_tag grocery.image_url_or_default, class: 'grocery-image' %>
	  <br>
		<strong><%= grocery.name %></strong>
	<% end %>
	<br>
	<% if user_id_matches_logged_user? %>
		<button class="stop-following-button" data-grocery-id="<%= grocery.id %>">Stop following</button>
		<div class="removing-container hidden">
			<%= image_tag "pIkfp.gif", class: 'left-floatme' %>
			<span>Removing from your following list ...</span>
		</div>
	<% end %>
</div>

app/views/groceries/_groceries_pagination.html.erb
<strong>Groceries</strong>
<%= will_paginate pagination_data, params: {controller: 'groceries', action: 'index'} %>  
<div class = "groceries_container">
	<%= render groceries %>
</div>
<%= will_paginate pagination_data, params: {controller: 'groceries', action: 'index'} %>

app/views/groceries/_grocery.html.erb
<div class="grocery_div">
	<%= link_to grocery_path(grocery) do %>
		<strong><%= grocery.name %></strong>
		<% if grocery.has_image? %>
		  <%= image_tag grocery.grocery_image.grocery_image_url, :style => "width: 120px; height: 120px;"  %>
		<% else %>
		  <%= image_tag "Springfield_grocery_store.png", :style => "width: 120px; height: 120px;"  %>
		<% end %>
	<% end %>
</div>

app/views/groceries/edit.html.erb
<h1>Edit Grocery</h1>

<%= render partial: 'shared/grocery_form', locals: {grocery: @grocery, namespace: grocery_path(@grocery), submit_message: 'Update Grocery'} %>

app/views/groceries/index.js.erb
$("#pagination_div").html("<%= escape_javascript(render(partial: "groceries/groceries_pagination", 
  locals: {groceries: @groceries, pagination_data: @pagination_data})) %> ");  

<%

  appended_parameters = "&page_count=" << @page_count.to_s
  #appended_parameters << "&search=" << params[:search] if @has_search_string

  #puts "----------------------------------------"
  #puts "----------------------------------------"
  #puts "@has_search_string = #{@has_search_string}"
  #puts "params[:search] = #{params[:search]}"
#
  #if @has_tags
  #  tags = params[:tags]
  #  tags.each do |tag|      
  #    next unless tag.is_a?(String) && tag.is_i?
  #    appended_parameters << "&tags[]=" << tag
  #  end
  #end
  #if @has_categories
  #  categories = params[:categories]
  #  categories.each do |cat|
  #    next unless  cat.is_a?(String) && cat.is_i?
  #    appended_parameters << "&categories[]=" << cat
  #  end
  #end
#
  #puts "appended_parameters = #{appended_parameters}"
  #puts "----------------------------------------"
  #puts "----------------------------------------"


  
%>

appended_parameters = "<%= appended_parameters.html_safe %>";

$('.pagination a').each(function() {
  var _href = $(this).attr("href");
  $(this).attr("href", _href + appended_parameters);
});

$('.pagination a').click(function () {  
    $('.pagination').html('Loading groceries...');  
    $.get(this.href, null, null, 'script');  
    return false;  
});

app/views/groceries/new.html.erb
<h1>New Grocery</h1>

<%= render partial: 'shared/grocery_form', locals: {grocery: @grocery, namespace: groceries_path, submit_message: 'Submit Grocery'} %>

<%= link_to 'Back', user_path(@logged_user) %>

app/views/groceries/search_products.html.erb
<div id = "grocery_products_pagination">
		<%= render partial: 'products/products_pagination_inside_grocery', locals: {products: @products, grocery: @grocery} %>
</div>

<script>
	refreshProductsPagination();
</script>

app/views/groceries/search_products.js.erb
$("#grocery_products_pagination").html("<%= escape_javascript(render partial: 'products/products_pagination_inside_grocery', locals: {products: @products, grocery: @grocery}) %> ");  

refreshProductsPagination();

app/views/groceries/show.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'home', media: :all %>
  <%= javascript_include_tag 'home' %>
<% end %>

<h1> Grocery Information </h1>

<div class='big-img-container left-floatme'>
  <% if @grocery.has_image? %>
    <%= image_tag @grocery.grocery_image.grocery_image_url %>
  <% else %>
    <%= image_tag "Springfield_grocery_store.png" %>
  <% end %>
</div>

<div class="grocery-info left-floatme">

  <p>
    <strong>Name:</strong>
    <%= @grocery.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @grocery.address %>
  </p>

  <div class="privileges">
  <% @users_per_privilege.keys.each do |key| %>

    <% users = @users_per_privilege[key] %>

    <strong><%= ((users.count > 1) ? key.pluralize : key).titleize %></strong>

    <div class="privilege-group">
      <% users.each do |user| %>
        <%= link_to user_path(user.id) do %>
          <div class='user-container left-floatme'>

            <% if user.has_image? %>
              <%= image_tag user.user_image.user_image_url, class: 'left-floatme' %>
            <% else %>
              <%= image_tag "default_profile.jpg", class: 'left-floatme' %>
            <% end %>
            <span class='right-floatme'> <%= user.username %> </span>

          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
  </div>
</div>

<div class="float-separator"></div>

<div id = "grocery_products_pagination">
    <%= render partial: 'products/products_pagination_inside_grocery', locals: {products: @products, grocery: @grocery} %>
</div>

<script>
  refreshProductsPagination();
</script>