config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  namespace :admin do
    resources :users
    resources :groceries
    resources :products
  end

  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :groceries do
    resources :products, controller: 'grocery_products'    
    resources :purchase_orders
    resources :reports
  end

  resources :reports, only:[] do
    resources :comments, only:[:index,:create], controller: 'report_comments'
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :products, only: [:index] do
    resources :reviews, only: [:show, :new, :create, :index, :edit, :update, :destroy]
  end


  match '/signup',    to: 'users#new',            via: 'get'
  match '/signin',    to: 'sessions#new',         via: 'get'
  match '/signout',   to: 'sessions#destroy',     via: 'delete'

  match '/groceries/:grocery_id/rate_product/:id', to: 'grocery_products#rate_product', via: 'post', as: 'rate_product'

  match '/groceries/:grocery_id/follow', to: 'groceries#follow', via: 'post', as: 'grocery_follow'
  match '/groceries/:grocery_id/unfollow', to: 'groceries#unfollow', via: 'post', as: 'grocery_unfollow'

  match '/reviews/:review_id/comments/new', to: 'review_comments#create', via: 'post', as: 'post_new_comment'
  match '/reviews/:review_id/comments', to: 'review_comments#index', via: 'get', as: 'review_comments'

  match '/groceries/:id/search_products', to: 'groceries#search_products', via: 'get', as: 'search_products'

  match '/search_groceries', to: 'search#groceries', via: 'get'
  match '/search_products',  to: 'search#products',  via: 'get'

  match '/users/:id/feed', to: 'users#news_feed', via: 'get', as:'user_news_feed'
  match '/users/:id/posted_news', to: 'users#posted_news', via: 'get', as: 'user_posted_news'
  match '/users/:id/following_groceries', to: 'users#following_groceries', via: 'get', as: 'user_following_groceries'
  match '/users/:id/associated_groceries', to: 'users#associated_groceries', via: 'get', as: 'user_associated_groceries'










end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :grocery
  belongs_to :product
  belongs_to :user
  has_many :comments, foreign_key: "report_id", class_name: "ReportComment", :dependent => :delete_all
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  include GroceryHelper
  layout 'groceries'

	before_action :set_logged_user_by_cookie
	before_action do set_grocery_by_id(:grocery_id) end
  before_action :set_privilege_on_grocery
	before_action :set_report_by_id, only:[:show, :edit, :update, :destroy]

  before_action do check_grocery_exists(:grocery_id) end
  before_action :check_user_logged_in, only: [:new, :create, :update, :destroy ]
  before_action only: [:new, :create, :edit, :update, :destroy] do check_privilege_on_grocery(:administrator, :grocery_id) end
  before_action :check_report_exists, only: [:edit, :update, :show]
  before_action :check_report_belongs_to_grocery, only: [:edit, :update, :show]

  def index
    @reports = @grocery.reports

    if params[:page]
      @reports = @reports.paginate(page: params[:page], per_page: 5)
    else
      @reports = @reports.paginate(page: 1, per_page: 5)
    end
  end

  def new
  	@report = Report.new
  end

  def create

    filtered_params = report_params
    filtered_params[:user_id] = @logged_user.id
    @report = Report.new(report_params)
    if @report.save
      flash[:success] = "News created successfully!"
      NotifyNewReportToFollowersJob.perform_later(@grocery,@report)
      redirect_to grocery_report_path(@grocery,@report)
    else
      render 'new'
    end

  end

  def show
      @per_page = 10
    @comments = @report.comments.order(id: :desc).limit(@per_page)
  end

  def edit
  end

  def update

    if @report.update(report_params)
      flash[:success] = 'News updated succesfully!'
      redirect_to grocery_report_path(@grocery,@report)
    else
      render 'edit'
    end
  end

  def destroy
		if(!@report.nil?)
			@report.destroy
			flash[:success] = "News destroyed successfully!"
		else
			flash[:error] = "News was nil"
		end
		redirect_to grocery_report_path(@grocery,@report)
	end


  private

  def set_report_by_id
    @report = Report.find_by_id(params[:id])
  end

  def check_report_belongs_to_grocery
    unless @report.grocery_id == @grocery.id
      raise ActionController::RoutingError.new("News with id #{params[:id]} does not belong to grocery with id #{params[:grocery_id]}")
    end
  end

  def check_report_exists
    unless @report
      raise ActionController::RoutingError.new("News with id #{params[:id]} not found")
    end
  end

  def report_params
    p = params.require(:report).permit(:title, :text);
    p[:grocery_id] = params[:grocery_id]
    p[:product_id] = params.require(:report)[:product]
    return p
  end

end

app/views/reports/_report.html.erb
<%#=  parameters: report, grocery, show_comments_link %>

<div class="report-container">
	<div class="spanner-container">
		<h3><%= report.title %></h3>

		<% if report.product %>
			<% if report.product.has_image? %>
				<%= image_tag report.product.product_image.product_image_url, style: "width: 100; height: 100px;"  %>
			<% else %>
				<%= image_tag "products-icon-basket.gif", :style => "width: 100px; height: 100px;"  %>
			<% end %>
		<% end %>

		<p>
			<%= image_tag "clock.png", style: "width: 12; height: 12px;" %>
			<span class="report-date" style="font-size: 12px; color: rgb(153, 0, 0);">
				<%= report.created_at.to_s.split[0..-2].join(' ') %>
			</span>
			<div style="font-size: 14px;"/>
				<%= simple_format(report.text) %>
			</div>
		</p>

		<% if report.product %>
			<a href="<%= grocery_product_path(grocery, report.product) %>">
				<span class="link-spanner"></span>
			</a>
		<% end %>
	</div>

	<% if is_administrator? %>
		<table class="report-admin">
			<tr>
				<td><%= link_to "Edit", edit_grocery_report_path(grocery, report) %></td>
				<td><%= link_to "Destroy", grocery_report_path(grocery, report), data: { confirm: "Are you sure?" , method: :delete } %></td>
			</tr>
		</table>
		<clear-fix></clear-fix>
	<% end %>

	<% if show_comments_link %>
		<%= link_to "All Comments (#{report.comments.count})", grocery_report_path(grocery, report) %>
	<% end %>

</div>

app/views/reports/_report_feed_pagination.html.erb
<%#= parameters: reports %>

<% reports.each do |report| %>
	<%= render partial: 'reports/report_for_feed', locals: {report: report, grocery: report.grocery, show_comments_link: true} %>
	<br>
<% end %>

app/views/reports/_report_for_feed.html.erb
<%#=  parameters: report, grocery, show_comments_link %>

<div class="report-container" id = '<%= report.id %>'>
	<div class="grocery-image-container">
		<%= link_to grocery_path(grocery) do %>
			<%= image_tag grocery.image_url_or_default, class: "grocery-image" %>
		<% end %>
	</div>
	<div class="right-container">
		<div class="report-header">
			<%= link_to grocery.name, grocery_path(grocery) %> posted by
			<%= link_to user_path(report.user) do %>
				<%= report.user.username %>
				<%= image_tag report.user.image_url_or_default, class: "author-image" %>
			<% end %>
			<br>
			<span>on <%= report.created_at.strftime("%a, %b %d %Y at %H:%M hrs") %></span>
		</div>
		<br>
		<%= link_to grocery_report_path(grocery,report) do %>
			<h3> <%= report.title %> </h3>
		<% end %>
		<pre class="text-container"><%= report.text %></pre>

		<% if report.product %>
			<span>Attached product: </span>			
			<div class="attached-product-container">
				<%= link_to grocery_product_path(grocery, report.product) do %>
					<%= image_tag report.product.image_url_or_default, class: "attached-image" %>
					<br>
					<span class="product-name"><%= report.product.name %></span>
				<% end %>
			</div>
			<br>
		<% end %>

		<% if show_comments_link %>
			<%= link_to "All Comments (#{report.comments.count})", grocery_report_path(grocery, report) %>
		<% end %>

	</div>
</div>

app/views/reports/_report_form.html.erb
<!-- remember to provide local variables product, namespace and submit_message -->

<%= form_for(report, url: namespace) do |f| %>

  <%= render 'shared/error_messages', object: report %>

  <div class = "field">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :text, "Text" %>
    <%= f.text_area :text %>
  </div>

  <div class="field">
    <%= f.label :product, "Product link: " %>
    <br>
    <%= f.select :product, options_for_select(Product.where(grocery_id: @grocery.id).collect {|p| [p.name,p.id]}, report.product ? report.product.id : nil ), {include_blank: true}, {class: 'awesome-select'} %>
  </div>

  <script>
    // make title and text look similar
    $("#report_text").css("font-family", $("#report_title").css("font-family"));
    $("#report_text").css("font-size", $("#report_title").css("font-size"));
  </script>

  <%= f.submit submit_message %>

<% end %>

app/views/reports/_reports_pagination.html.erb
<%= will_paginate @reports, params: {controller: 'reports', action: 'index', grocery_id: @grocery.id} %>
<% @reports.each do |report| %>
	<%= render partial: 'report', locals: {report: report, grocery: @grocery, show_comments_link: true} %>
	<br>
<% end %>
<%= will_paginate @reports, params: {action: 'index', grocery_id: @grocery.id} %>

app/views/reports/edit.html.erb
<h1>Edit News</h1>

<%= render partial: 'reports/report_form', locals: {report: @report, namespace: grocery_report_path(@grocery, @report), submit_message: 'Update News'} %>

app/views/reports/index.html.erb
<h2>News</h2>
<% if @privilege == :administrator %>
  <%= link_to 'Create a news', new_grocery_report_path(@grocery) %>
	<br>
	<br>
<% end %>

<div id = "reports_pagination">
	<%= render("reports_pagination") %>
</div>

app/views/reports/index.js.erb
$("#reports_pagination").html("<%= escape_javascript(render("reports_pagination")) %>");  

app/views/reports/new.html.erb
<h1>Create a news</h1>

<%= render partial: 'report_form', locals: {report: @report, namespace: grocery_reports_path(@grocery), submit_message: 'Submit News'} %>

app/views/reports/show.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'reports' %>
<% end %>

<h3>News</h3>

<%= render partial: 'report', locals: {report:  @report, grocery: @grocery, show_comments_link: false} %>


<% if signed_in? %>

	<div id="new_comment_div">
		<div id="add_comment_div">
			<button onclick="showNewCommentForm()">Add a comment</button>
		</div>
		<div id="post_comment_div" class="hide-element">

			<%= form_tag report_comments_path(@report), method: 'post', remote: true, id: 'new_comment_form' , onsubmit:  'commentFormSubmit_clicked()' do %>
				<fieldset>
					<div id="errors"></div>
					<%= text_area_tag :content, nil, required: true %>
					<br>
					<%= submit_tag "Post comment" %>
					<button type="button" name="cancel" onclick="cancelNewComment()">Cancel</button>
				</fieldset>
			<% end %>

		</div>
	</div>

<% end %>




<hr>
<h3 id="comment-section-title"> Comments (<%= @comments.count %>)</h3>

<div id = "comments_div">
	<%= render partial: 'report_comments/report_comments_pagination', locals: {comments: @comments } %>
</div>

<br>

<% if @comments.count == @per_page %>
	<button id = "more_comments_button" onclick="showMoreComments(this)" data-url = "<%= report_comments_url(@report) %>" > Show more comments </button>
<% else %>
	<button id = "more_comments_button" disabled>No more comments available</button>
<% end %>